name: Check and Un paid Installments for Schools

on:
  workflow_dispatch:
    branches: [main]
  schedule:
    - cron: "30 0 * * *"
jobs:
  installments-pipeline:
    name: Check and Unpaid Installments for All Schools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Give executive permissions
        run: |
          chmod +x ./check_installments.sh
      - name: Run the Installments Check Script
        run: |
          ./check_installments.sh