name: test backup script

on:
  workflow_dispatch:
    branches: [main]
  # schedule:
  #   - cron: "30 22 * * *"

jobs:
  backup-pipeline:
    name: Backup Script for Medisparsh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ✅ Add PostgreSQL official repo
      - name: Install PostgreSQL client 15
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Verify pg_dump
        run: pg_dump --version

      - name: Install DO Spaces CLI
        run: npm install -g spaces-cli

      # ✅ Backup + upload
      - name: Run backup and upload to DO Spaces
        env:
          PGPASSWORD: your-super-secret-and-long-postgres-password
          DO_SPACE_KEY: DO00Z6BQLU76298YFU2G
          DO_SPACE_SECRET: l3XB9ck+U9tvwixHGxMopTFVWSJlwxxpOlNJhvlQhIo
        run: |
          pg_dump \
            -h studio.maitretech.com \
            -p 5432 \
            -U postgres \
            -d postgres \
            --schema auth \
            -f auth.sql

          spaces-cli up \
            -s schoolerp-bucket \
            -r blr1 \
            -i "$DO_SPACE_KEY" \
            -k "$DO_SPACE_SECRET" \
            -t schoolscoop-supa/auth/test \
            auth.sql
